package grokrun

import (
	"bufio"
	"bytes"
	"context"
	"fmt"
	"io"
	"strings"
)

// driver holds everything that differs between coding CLIs. Process lifecycle,
// timeouts, process-group kill, and Result assembly stay in Run.
type driver interface {
	// streamFormat is the --output-format value for streaming runs.
	streamFormat() string
	// promptOnStdin reports whether the prompt is piped to the child rather than
	// handed over as a file path.
	promptOnStdin() bool
	// args builds the child argv (binary excluded).
	args(in argInput) []string
	// childEnv applies agent-specific environment adjustments.
	childEnv(env []string) []string
	// prebindSession reports whether Run should generate a session id before
	// starting the child. Only needed by drivers that learn tool activity from a
	// session file keyed by that id.
	prebindSession(opt Options) bool
	// decodeLine folds one line of streaming output into acc.
	decodeLine(line []byte, acc *streamAccum)
	// decodeFinal parses the whole-output JSON of a non-streaming run.
	// ok is false when stdout is not the expected JSON shape.
	decodeFinal(stdout []byte) (out finalOut, ok bool)
	// watchActivity tails an out-of-band activity source until ctx is done.
	watchActivity(ctx context.Context, cwd, sessionID string, onActivity func(string))
	// enrich fills context-window fields that the stream did not carry.
	enrich(res *Result, cwd string)
	// sessionAlreadyExists reports whether a failed run failed *only* because the
	// session id it was told to create is already taken, meaning the same id can
	// be resumed instead. See Run's retry.
	sessionAlreadyExists(res Result) bool
	// sessionMissing is the mirror: the run failed only because the session it was
	// told to resume does not exist, so the same id can be created instead.
	sessionMissing(res Result) bool
}

// argInput is the pure input for building a child argv.
type argInput struct {
	opt        Options
	promptPath string
	format     string
	// runSessionID is opt.SessionID when resuming, or a Run-generated id when
	// prebound. Empty means "let the CLI pick".
	runSessionID string
	// prebound is true when runSessionID was generated by Run rather than supplied
	// by the caller.
	prebound bool
}

// finalOut is the parsed result of a non-streaming run.
type finalOut struct {
	Text            string
	SessionID       string
	Usage           *Usage
	NumTurns        int
	MaxTurnsReached bool
}

type streamCallbacks struct {
	onText     func(string)
	onThought  func(string)
	onActivity func(string)
	// cwd is the run's working directory. Activity lines are shown in Discord and
	// must never carry a local path (see CLAUDE.md), so drivers whose tool payloads
	// are absolute report them relative to this.
	cwd string
}

// streamAccum collects decoded stream events. Drivers call its methods instead
// of touching streamOut so the "append text, fire callback, announce max-turns
// exactly once" rules stay in one place.
type streamAccum struct {
	cb  streamCallbacks
	b   strings.Builder
	out streamOut

	maxTurnsNotified bool
	parseNotes       []string
	// sawDelta records that incremental text arrived, so drivers that also emit a
	// final aggregated copy of the same text can skip it.
	sawDelta bool
	// inDelta is true while incremental chunks of the current assistant message
	// are arriving. finishDelta marks that message complete so the next delta
	// starts a new paragraph instead of gluing onto the last word.
	inDelta bool
	// msgStart is the byte offset in b of the current assistant message, after
	// any paragraph break inserted by separate. Used to recognize an assembled
	// copy of that message even when the model text itself contains blank lines.
	msgStart int
}

func (a *streamAccum) text(delta string) {
	if delta == "" {
		return
	}
	a.b.WriteString(delta)
	if a.cb.onText != nil {
		a.cb.onText(delta)
	}
}

// delta records incremental text (as opposed to a final aggregate).
func (a *streamAccum) delta(d string) {
	if d == "" {
		return
	}
	a.sawDelta = true
	a.inDelta = true
	a.text(d)
}

func (a *streamAccum) finishDelta() {
	a.inDelta = false
}

func (a *streamAccum) currentMessage() string {
	s := a.b.String()
	if a.msgStart <= 0 || a.msgStart > len(s) {
		return s
	}
	return s[a.msgStart:]
}

func (a *streamAccum) thought(delta string) {
	if delta != "" && a.cb.onThought != nil {
		a.cb.onThought(delta)
	}
}

func (a *streamAccum) activity(line string) {
	if line != "" && a.cb.onActivity != nil {
		a.cb.onActivity(line)
	}
}

// separate starts a new paragraph before the next text, so consecutive assistant
// messages in one run do not run together. No-op before any text has arrived.
func (a *streamAccum) separate() {
	if a.b.Len() == 0 {
		a.msgStart = 0
		return
	}
	a.text("\n\n")
	a.msgStart = a.b.Len()
}

// maxTurns marks the run as turn-limited and appends the user-facing notice once.
func (a *streamAccum) maxTurns() {
	a.out.MaxTurnsReached = true
	if a.maxTurnsNotified {
		return
	}
	a.maxTurnsNotified = true
	delta := MaxTurnsUserMessage
	if a.b.Len() > 0 {
		delta = "\n\n" + MaxTurnsUserMessage
	}
	a.text(delta)
}

func (a *streamAccum) session(id string) {
	if id != "" {
		a.out.SessionID = id
	}
}

func (a *streamAccum) usage(u *Usage) {
	if u != nil {
		a.out.Usage = u
	}
}

func (a *streamAccum) turns(n int) {
	if n > 0 {
		a.out.NumTurns = n
	}
}

func (a *streamAccum) context(used, window int) {
	if used > 0 {
		a.out.ContextTokensUsed = used
	}
	if window > 0 {
		a.out.ContextWindowTokens = window
	}
}

func (a *streamAccum) note(err error) {
	if err != nil {
		a.parseNotes = append(a.parseNotes, err.Error())
	}
}

// errorText folds a CLI-reported error message into the transcript, treating a
// max-turns message as the turn-limit signal rather than as output.
func (a *streamAccum) errorText(msg string) {
	if isMaxTurnsError(msg) {
		a.maxTurns()
		return
	}
	if msg == "" {
		return
	}
	if a.b.Len() > 0 {
		a.text("\n\n" + msg)
		return
	}
	a.text(msg)
}

func (a *streamAccum) finish() (streamOut, error) {
	a.out.Text = a.b.String()
	if len(a.parseNotes) > 0 {
		return a.out, fmt.Errorf("skipped %d malformed lines (e.g. %s)", len(a.parseNotes), a.parseNotes[0])
	}
	return a.out, nil
}

// decodeStream reads newline-delimited events until EOF, delegating each line to
// the driver. A scan error wins over accumulated parse notes.
func decodeStream(r io.Reader, d driver, cb streamCallbacks) (streamOut, error) {
	sc := bufio.NewScanner(r)
	sc.Buffer(make([]byte, 0, 64*1024), 10*1024*1024)

	acc := &streamAccum{cb: cb}
	for sc.Scan() {
		line := bytes.TrimSpace(sc.Bytes())
		if len(line) == 0 {
			continue
		}
		d.decodeLine(line, acc)
	}
	out, noteErr := acc.finish()
	if scanErr := sc.Err(); scanErr != nil {
		return out, scanErr
	}
	return out, noteErr
}
